### ISSUE TITLE
群消息弹窗挺烦的

### ISSUE THREAD

**Issue by ghost** [xiehuc/pidgin-lwqq#282]
OS: Ubuntu 13.04 64bit with Unity Desktop
Pidgin Version : 2.10.7
Lwqq : current 

Issue: 能不能QQ群来消息不自动弹出来？烦死了
1、我在首选项里面设置了「总是」对群消息好像没用
2、不想屏蔽群消息
3、我只想让他不弹出来在托盘的信封里面显示就好

**Comment by cilongxiang** [comment]
@xiehuc 接收不提示还是会弹出群窗口的啊，感觉老是弹窗很不舒服

**Comment by mhohai** [comment]
@cilongxiang 你是不是又要说你在Windows下设置了？
pidgin难道没有屏蔽！

**Comment by lainme** [comment]
@cilongxiang 你看看设置后群的名字是不是被括号括着，如果是就表示在pidgin里设置成功了。我刚才创建了一个群测试了一下，似乎不能正常的更改屏蔽设置，但之前设置过的都有效。

**Comment by lainme** [comment]
@cilongxiang 你看一下设置后群名称有没有被括号括着，如果有说明设置成功。我刚创建了一个群测试了一下，似乎不能正常更改屏蔽设置，但是以前设置过的没有问题。

**Comment by mhohai** [comment]
@lainme 我测试了下，不能正常设置了，这个是pidgin的问题，还是插件的问题？

**Comment by lainme** [comment]
@mhohai 不确定。我试着开webqq测试，但是连不上，终端输出似乎是response null

**Comment by mhohai** [comment]
我用网页打开[webqq](http://w.qq.com) 压根没有设置这项。。。
新建了个群：112104389  测试无法屏蔽...

**Comment by cilongxiang** [comment]
@lainme 不行啊，根本就没有括号

**Comment by cilongxiang** [comment]
@lainme 你以前设置的，是什么意思啊

**Comment by xiehuc** [comment]
ok，我待会儿改成本地数据库的。

主要是github的邮件都被当成垃圾邮件了。现在才看到。。。

El Psy Congroo

在 2015年1月10日，00:33，cilongxiang <notifications@github.com> 写道：
