### ISSUE TITLE
启动时奔溃

### ISSUE THREAD

**Issue by o3o3o** [xiehuc/pidgin-lwqq#589]
以下是用gdb方式启动的过程：

Sep 15 09:50:48] WARNING[17227]: http.c:657 check_multi_info: 
	async retcode:47
[Sep 15 09:50:48] WARNING[17227]: http.c:657 check_multi_info: 
	async retcode:47
process 17227: arguments to dbus_message_new_method_call() were incorrect, assertion "_dbus_check_is_valid_path (path)" failed in file ../../dbus/dbus-message.c line 1204.
This is normally a bug in some application using the D-Bus library.
process 17227: arguments to dbus_message_iter_init_append() were incorrect, assertion "message != NULL" failed in file ../../dbus/dbus-message.c line 2284.
This is normally a bug in some application using the D-Bus library.
process 17227: dbus message iterator looks uninitialized or corrupted
process 17227: arguments to dbus_message_iter_open_container() were incorrect, assertion "_dbus_message_iter_append_check (real)" failed in file ../../dbus/dbus-message.c line 2716.
This is normally a bug in some application using the D-Bus library.
process 17227: dbus message iterator looks uninitialized or corrupted
process 17227: arguments to dbus_message_iter_open_container() were incorrect, assertion "_dbus_message_iter_append_check (real)" failed in file ../../dbus/dbus-message.c line 2716.
This is normally a bug in some application using the D-Bus library.
process 17227: dbus message iterator looks uninitialized or corrupted
process 17227: arguments to dbus_message_iter_append_basic() were incorrect, assertion "_dbus_message_iter_append_check (real)" failed in file ../../dbus/dbus-message.c line 2521.
This is normally a bug in some application using the D-Bus library.
process 17227: dbus message iterator looks uninitialized or corrupted
process 17227: arguments to dbus_message_iter_open_container() were incorrect, assertion "_dbus_message_iter_append_check (real)" failed in file ../../dbus/dbus-message.c line 2716.
This is normally a bug in some application using the D-Bus library.

Program received signal SIGSEGV, Segmentation fault.
0xb7f87e96 in ?? () from /lib/i386-linux-gnu/libdbus-1.so.3

-------下面是bt full打印结果-------
0xb7f87e96 in ?? () from /lib/i386-linux-gnu/libdbus-1.so.3
No symbol table info available.
#1  0xb7f87f0d in ?? () from /lib/i386-linux-gnu/libdbus-1.so.3
No symbol table info available.
#2  0xb7f89f81 in dbus_message_iter_append_basic ()
   from /lib/i386-linux-gnu/libdbus-1.so.3
No symbol table info available.
#3  0xb441bf7c in ?? () from /usr/lib/i386-linux-gnu/libgnome-keyring.so.0
No symbol table info available.
#4  0xb4421f64 in gnome_keyring_item_create ()
   from /usr/lib/i386-linux-gnu/libgnome-keyring.so.0
No symbol table info available.
#5  0xb4422d25 in gnome_keyring_store_password ()
   from /usr/lib/i386-linux-gnu/libgnome-keyring.so.0
No symbol table info available.
#6  0xb54b5d19 in ?? () from /usr/lib/purple-2/gnome-keyring.so
No symbol table info available.
#7  0xb4415e42 in ?? () from /usr/lib/i386-linux-gnu/libgnome-keyring.so.0
No symbol table info available.
#8  0xb441fbd2 in ?? () from /usr/lib/i386-linux-gnu/libgnome-keyring.so.0
No symbol table info available.
#9  0xb4415990 in ?? () from /usr/lib/i386-linux-gnu/libgnome-keyring.so.0
No symbol table info available.
---Type <return> to continue, or q <return> to quit--- 
#10 0xb4418094 in ?? () from /usr/lib/i386-linux-gnu/libgnome-keyring.so.0
No symbol table info available.
#11 0xb44188f9 in ?? () from /usr/lib/i386-linux-gnu/libgnome-keyring.so.0
No symbol table info available.
#12 0xb7f8fa71 in ?? () from /lib/i386-linux-gnu/libdbus-1.so.3
No symbol table info available.
#13 0xb7f7a957 in ?? () from /lib/i386-linux-gnu/libdbus-1.so.3
No symbol table info available.
#14 0xb7f7e237 in dbus_connection_dispatch ()
   from /lib/i386-linux-gnu/libdbus-1.so.3
No symbol table info available.
#15 0xb4424cfd in ?? () from /usr/lib/i386-linux-gnu/libgnome-keyring.so.0
No symbol table info available.
#16 0xb758fd46 in g_main_context_dispatch ()
   from /lib/i386-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#17 0xb75900e5 in ?? () from /lib/i386-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#18 0xb759052b in g_main_loop_run () from /lib/i386-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#19 0xb79cdbff in gtk_main () from /usr/lib/i386-linux-gnu/libgtk-x11-2.0.so.0
No symbol table info available.
#20 0x80028c58 in main ()
---Type <return> to continue, or q <return> to quit---
No symbol table info available.

**Comment by xiehuc** [comment]
这个初步看是 pidgin-gnome-keyring 插件有bug
