### ISSUE TITLE
可以说说这个项目现在的状况吗？

### ISSUE THREAD

**Issue by gansteed** [xiehuc/pidgin-lwqq#607]
上次腾讯宣布关闭webQQ时看到作者说不准备继续维护了， 但是看到最近的更新是18天之前。 可以说说这个项目目前的状况吗？

**Comment by mhohai** [comment]
@jizhongling  前三楼

**Comment by EricInBj** [comment]
@mhohai  好友发的图片能显示是因为前段时间 @xiehuc 改了代码，跟进了webqq的变更，见这个 #586

**Comment by EricInBj** [comment]
@mhohai  另外，替换IM的事儿不容易。。。不是技术问题，而是你身边的人用什么。。改变自己容易，改变别人不易。

**Comment by mhohai** [comment]
@EricInBj 要微信，要人人，我意思：要的可口，自己动手...
