### ISSUE TITLE
如果有一天这个项目因为腾讯不能用了，我们集体转到另一款IM队伍吧...

### ISSUE THREAD

**Issue by mhohai** [xiehuc/pidgin-lwqq#608]
欢迎大家以中立的态度推荐任何IM，欢迎讨论，大家一起转，才是真的转。
我就不信，用Linux的拉不到人！！！

**Comment by jizhongling** [comment]
或许可以考虑来个pidgin-人人，感觉我的人人好友比QQ好友还多，不过人人没有好的客户端，好友在线率太低。

**Comment by Rivsen** [comment]
我最近再在用telegram

**Comment by R32** [comment]
我推荐用 IRC , 使用 freenode 的服务器, IRC Bot 蛮好玩的应该可以吸引很多人

**Comment by mhohai** [comment]
@R32 你要考虑下有人需要私密聊天的啊...

**Comment by linux0ne** [comment]
这个话题当作闲扯，还是可以灌灌水的。
1、且不说现在QQ有多少用户，也不讲pidgin-lwqq有了多少拥趸，最主要的是你要更改得是人们的生活习惯。
2、习惯这东西 ，如果没有，你可以容易的去建立，可一旦建立了，相当难清除，更何况QQ已经成了一种产业链，有多少人天天用这东西赚钱呢
3、回到你这个话题的操作性上来看，替代软件N多，各方面功能都完备的，安全性受黑客垂青的uTox就可以，比skype全球声誉还强。
4、记住，改一个群体的思维是需要从根源上动摇的，这根源不是拿一个功能和效果更好的同类产品去强势替代它，这根源是重新培养他另一种习惯，原有的习惯不理睬。当一种习惯产生了，比如爱上了抽烟，那么时机成熟了。

胡谄一下，勿喷。

**Comment by MX1913** [comment]
我也简单地说下我的看法。
首先我登陆QQ的时间越来越少，我相信QQ的用户群必然是固定的，再扩展的可能比较小。
其次微信的大肆扩张抢走了不少QQ的用户，尤其是在移动端的。
腾讯关闭webQQ是出于业务考量，并不会因为群众的呼声而改变。
从工作的角度来讲，QQ并不是很高效的沟通工具。企业用户会采用RTX之类的软件。
现在微信出了web版和客户端，也许微信是个接口。。。
以上是我个人瞎掰的。不喜勿喷。

**Comment by R32** [comment]
IRC 可以密语啊...

**Comment by amitbha** [comment]
QQ会不惜一切代价干掉你。。。

**Comment by mhohai** [comment]
@amitbha 好怕怕！
