### ISSUE TITLE
最近老是发送消息失败

### ISSUE THREAD

**Issue by xibeisiber** [xiehuc/pidgin-lwqq#609]
以前都很正常，最近老是出现发送消息失败的情况

**Comment by EricInBj** [comment]
上个月有段时间我的失败率非常高，基本上是登录上去能发个几条，然后就不行了，退出重登录才可以。。。

**Comment by xibeisiber** [comment]
嗯，之前老是发送失败后我用模拟器了，用了一段时间感觉不太方便又回来了，现在基本没啥问题了
