### ISSUE TITLE
十分好用，祈祷能存在的久一点

### ISSUE THREAD

**Issue by jizhongling** [xiehuc/pidgin-lwqq#610]
前两天才发现这个插件，认真看了所有Wiki，几乎所有功能都能顺利地使用。而且感觉这个插件功能很多，设计的也十分专业，真的是太喜欢了。但是听说WebQQ协议就要被关闭了，估计这个插件也马上就要不能用了。新年第一天在这里祈祷一下，希望腾讯能回心转意，不要关闭WebQQ。

**Comment by mhohai** [comment]
感谢你的反馈，不过我还想[干掉腾讯](https://github.com/xiehuc/pidgin-lwqq/issues/608)
