### ISSUE TITLE
我想了解一下telepathy-lwqq插件的使用

### ISSUE THREAD

**Issue by djunhao** [xiehuc/pidgin-lwqq#611]
我想直接使用telepathy-lwqq，但是在该项目上没有看到相关的安装设置说明。所以就到这里来提问了，抱歉。
目前，我已编译安装了lwqq（git）和telepathy-lwqq(git)，安装目录是均为cmake脚本默认安装目录，请问，应该如何设置empathy添加qq帐号？
谢谢！

**Comment by mhohai** [comment]
我个人建议用pidgin，编译的问题相信会有人回答。
以下引用：
>
* telepathy-haze 本身不支持群组聊天和图片显示.比较纠结.
telepathy-haze 比较坑爹.居然不保存好友列表.!!
它只在/tmp/haze-XXXXXX 存放下文件.
所以速度非常受影响.
不知道为什么要这样设计.

**Comment by djunhao** [comment]
我就是想直接使用telepathy-lwqq插件，而不是通过telepathy-haze桥接使用pidgin-lwqq。至于lwqq和telepathy-lwqq已经make && make install，但是在empathy中无法看到lwqq的相关帐号设置。
至于pidgin，它所依赖的gstreamer是0.10版本的，我系统中已经安装了1.x版本的，虽然可以共存，但是不喜欢如此复杂的依赖环境。

**Comment by mhohai** [comment]
@djunhao 不好意思，我不会...  建议多从看看现有的wiki之类的，然后从原理摸索

**Comment by xiehuc** [comment]
telepathy-lwqq就是个坑，没写完的。

El Psy Congroo

在 2015年1月4日，23:06，djunhao <notifications@github.com> 写道：

**Comment by linux0ne** [comment]
@djunhao  你放弃这种想法和做法吧，我试验过，一点意义没有，你会反复的头疼。
