### ISSUE TITLE
怎样禁止收到群消息时聊天窗口自动弹出

### ISSUE THREAD

**Issue by AlexLuya** [xiehuc/pidgin-lwqq#612]
你好，我用的是ubuntu,已将perference->interface->Conversation window hide new IM conversations设置成always,但还是自动弹出。

**Comment by mhohai** [comment]
@AlexLuya 我测试了啊，设置后确实没有弹出！

你是不是理解错弹出了，没有弹出窗口，可Ubuntu的那个提醒是有的。。。
还有，这个如果真的出问题了，也是pidgin的设置问题。

**Comment by AlexLuya** [comment]
“Ubuntu的那个提醒”是黑底白字，以前老通知：谁给我发消息了，谁上／下线了之类的，我已经关掉了。现在弹出的是聊天窗口，就是这个：

![workspace 1_100](https://cloud.githubusercontent.com/assets/303353/5609310/33ec5a28-94d8-11e4-997e-1a2963536f92.png)

我测试了，个人对个人的聊天消息不会自动弹出，但群聊天消息会。

**Comment by AlexLuya** [comment]
我已经在windows下将群消息设置为：接收但不显示。

**Comment by mhohai** [comment]
@AlexLuya 不知道你这在Windows下设置什么意思，是还有问题还是解决了问题。

**Comment by AlexLuya** [comment]
这个问题在ubuntu＋pidgin中依然存在。
　　“不知道你这在Windows下设置什么意思”，我的是意思是：在windows下打开ＱＱ，选中相应的群，然后点右键－》消息设置－》选择“仅显示消息数量”（个别字可能与原选项有差异）。这样设置后，用腾讯ＱＱ登录ＱＱ，刚被设置的群里即便有人发言了，我也不会看到任何消息。这样做是先排除ＱＱ设置不当这种可能性。
　　
　　这个问题也可以表述为：pidgin中选中相应的群－》右键－》block->slience receive(我把这个理解成“安静的接收”，即：收到也不提示。如果我理解正确的话，“slience”应该是"silence",“l”应该与“i”换下顺序)后仍然非常不“silence"。

**Comment by oncereply** [comment]
我这也是,有两个群的群消息会一直弹出,不过其它群的群消息又没有弹出...有点搞不懂~

**Comment by mhohai** [comment]
在pidgin中设置屏蔽...

**Comment by mhohai** [comment]
2012-9-25，这个功能是支持的[commit](https://github.com/xiehuc/pidgin-lwqq/commit/3b55323cdc70c3e77560062aa5a7e246da051b87)，如今无法设置，不知道在Windows下设置是否可以？

@lainme 你屏蔽过的群，再此屏蔽时默认选中第几个，见截图。我的无论设置多少次，默认都是第一个。  ![block chat](https://clbin.com/rLLcV1.png)

>
[move](https://github.com/xiehuc/pidgin-lwqq/issues/282)

**Comment by lainme** [comment]
@mhohai 我觉得不是改数据库的问题，还是和webqq的群屏蔽调用有关，那个接口可能已经没有了。具体的需要看代码里的实现。现在没什么时间，只能过几天再看

**Comment by oncereply** [comment]
@lainme 我觉得可以换种方法实现,不是一定要调用接口的实现,这个功能完全可以本地实现的嘛,使用本地配置,被屏蔽的群不再弹出窗口,那些消息有没有在服务器上被屏蔽,用户一般是不关注的

**Comment by xiehuc** [comment]
web接口失效了？
对于这个问题，我自己是设置的来消息了不自动focus窗口，也就是虽然弹窗，但不会遮挡，就等它在后面慢慢刷新了。
的确本地设置屏蔽可以解决。但配置不能同步

El Psy Congroo

在 2015年1月11日，19:34，答复哈 <notifications@github.com> 写道：

**Comment by linux0ne** [comment]
@mhohai   你调试.db文件时用得软件是什么名字？

**Comment by xiehuc** [comment]
我在dev分支将屏蔽组的功能移动到了本地数据库。 各位有空可以测试下。

**Comment by AlexLuya** [comment]
折腾了半天，也没法编译，错误如下：

````
--   package 'purple' not found
CMake Error at /usr/share/cmake-2.8/Modules/FindPkgConfig.cmake:283 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPkgConfig.cmake:337 (_pkg_check_modules_internal)
  CMakeLists.txt:21 (pkg_check_modules)


-- checking for module 'glib-2.0'
--   found glib-2.0, version 2.40.2
-- checking for module 'lwqq>=0.4.2'
--   package 'lwqq>=0.4.2' not found
CMake Error at /usr/share/cmake-2.8/Modules/FindPkgConfig.cmake:283 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPkgConfig.cmake:337 (_pkg_check_modules_internal)
  CMakeLists.txt:23 (pkg_check_modules)


libpurple version:Package purple was not found in the pkg-config search path.
Perhaps you should add the directory containing `purple.pc'
to the PKG_CONFIG_PATH environment variable
No package 'purple' found
libpurple version outdate
-- Found Gettext: /usr/bin/msgmerge (found version "0.18.3") 
CMake Error at src/CMakeLists.txt:41 (install):
  install TARGETS given no LIBRARY DESTINATION for module target "webqq".


===============pidgin-lwqq flags===============
-- Native Language Support : true
-- Install Path            : 
===============================================
-- Configuring incomplete, errors occurred!
See also "/home/alex/Software/pidgin-lwqq/build/CMakeFiles/CMakeOutput.log".
````

**Comment by lainme** [comment]
@AlexLuya 需要先编译并安装lwqq，然后再编译并安装pidgin-lwqq。编译依赖和编译方法可以参考

https://github.com/xiehuc/lwqq/wiki/Build-From-Source
https://github.com/xiehuc/pidgin-lwqq/wiki/Install-From-Source

**Comment by mhohai** [comment]
@linux0ne 工具是：Sqliteman  辞职回家了，然后一直没看见。。。
好长一段时间没上线的表示，，，。。。  不过如今会来了 T_T
