### ISSUE TITLE
win版本插件，不能打开空间

### ISSUE THREAD

**Issue by binai** [xiehuc/pidgin-lwqq#614]
在打开空间时，会出现调用错误，请问这是调用的什么浏览器来打开的？
如何修改呢？

![image](https://cloud.githubusercontent.com/assets/5106130/5788448/40657fee-9e71-11e4-8718-e97fdf480e94.png)

![image](https://cloud.githubusercontent.com/assets/5106130/5788452/82361168-9e71-11e4-8d6c-714b234e403f.png)

**Comment by mhohai** [comment]
lwqq调用pidgin，pidgin调用系统。
建议你试试pidgin打开其它链接看看，初步判断在windows下设置打开方式可解决。

**Comment by xiehuc** [comment]
我用的start程序，但我不知道实际该用什么。

El Psy Congroo

在 2015年1月17日，17:52，binai <notifications@github.com> 写道：
