### ISSUE TITLE
2015年01月21日20:20:41 无法登陆

### ISSUE THREAD

**Issue by noobfish** [xiehuc/pidgin-lwqq#616]
上午还能登陆，晚上这会就不行了。反复试了很多次，都说账号或者密码错误。我为此专门修改了密码，重新登陆输入验证码还是这样。请问大家登陆正常么？若你们可以正常使用，就说明是我自己的问题了.

**Comment by nolouch** [comment]
我连Web QQ协议都没找到，哪有问题吗

**Comment by felixonmars** [comment]
@noobfish 我这里登陆了 4 个号, 有一个号有一模一样的问题. 我重试登陆很多很多次后, 突然成功了.

**Comment by nolouch** [comment]
我改了，一样是登陆账号密码错误。腾讯换协议了？

**Comment by jizhongling** [comment]
我也在相同时间突然不能登陆了

**Comment by foxprodos** [comment]
一样的问题。。

**Comment by binai** [comment]
同样的问题，上午还可以，上午就不行了。

**Comment by floating-cat** [comment]
+1

**Comment by oncereply** [comment]
+1

**Comment by asmca** [comment]
+1



with or without http proxy, both failed.

showup captcha again and again, with passwd failed error.

seems QQ changed some protocal on Captcha verification.

-suse

[Jan 22 11:09:06] ERROR[3620]: login.c:744 lwqq_logout:
Send logout request failed
We need verify code image: h
[Jan 22 11:09:14] WARNING[3620]: login.c:622 login_stage_3:
Need to enter verify code
[Jan 22 11:09:19] ERROR[3620]: login.c:351 do_login_back:
Wrong password
We need verify code image: h
[Jan 22 11:09:40] WARNING[3620]: login.c:622 login_stage_3:
Need to enter verify code
[Jan 22 11:09:45] ERROR[3620]: login.c:351 do_login_back:
Wrong password
We need verify code image: h
[Jan 22 11:11:05] WARNING[3620]: login.c:622 login_stage_3:
Need to enter verify code
[Jan 22 11:11:10] ERROR[3620]: login.c:351 do_login_back:
Wrong password
We need verify code image: h
[Jan 22 11:13:48] WARNING[3620]: login.c:622 login_stage_3:
Need to enter verify code
[Jan 22 11:13:55] ERROR[3620]: login.c:351 do_login_back:
Wrong password




Im using
pidgin-2.10.9-1.el7.x86_64
lwqq Version: 0.3.1

and
pidgin-2.10.7 on fc15
lwqq Version: 0.3.1

both failed.

**Comment by EricInBj** [comment]
我这两个帐号也一样的问题了，说帐号或密码错误，但直接到 web.qq.com上老版入口登录没问题。
狗日的腾讯

**Comment by trlsmax** [comment]
一样的问题

**Comment by juvevood** [comment]
今天登录确实有问题，多试几次还是可以的

**Comment by EricInBj** [comment]
完了，这会儿我重复了二十来次也没成功。。。。。。

**Comment by chengdongdong** [comment]
像是腾讯换协议了，这两天一直提示帐号密码错误

**Comment by EricInBj** [comment]
看了一下webqq的登录请求，似乎是URL参数里面的p 变化了， lwqq的 q是个 MD5但webqq是个很长的字符串。

**Comment by nolouch** [comment]
求解决方案

**Comment by noobfish** [comment]
朋友们，我每次登陆都要反复重试好几次。和大家一样，腾讯不增加新功能，净给大家添乱啊。还有楼上的兄弟，和国人交流就没必要用英文了吧。

**Comment by EricInBj** [comment]
一上午没登录上，刚才居然一下子成功了。。。。

**Comment by noobfish** [comment]
有没有可能用SmartQQ的协议来重新开发呢，这样的工作量是不是太大了？腾讯这么小家子气。

**Comment by jrdriscoll** [comment]
I find that if I have to enter the captcha I get the incorrect password error, but if I  reconnect via reconnect button on the bottom of the Pidgin Buddy list, it reliable connects. (Pidgin 2.10.3/libpurple 2.10.3/liblwqq 0.4.1)

Additionally, it is my understanding that the SmartQQ product will indefinitely continue, so reversing the SmartQQ protocol would be a long term solution, although it does not provide complete functionality.

**Comment by Lavande** [comment]
确实无法登录，提示密码错误
webqq网页可以登录

**Comment by shmilee** [comment]
我是今天才遇到同样的问题

**Comment by xiehuc** [comment]
sorry，github发的邮件被当成垃圾邮件了，我现在才看到，待会儿去修改去。

El Psy Congroo

在 2015年1月24日，22:59，shmilee <notifications@github.com> 写道：

**Comment by xiehuc** [comment]
新的加密算法都用上RSA了. 感觉out了.

**Comment by smallCC** [comment]
+1

**Comment by shenwei356** [comment]
@xiehuc  辛苦了

**Comment by xiehuc** [comment]
直接用了tx官方的js, 丢给spidermonkey来加密密码, 服务器还是不认. 我已经不知道该怎么办了...

暂且还是先提交个commit好了.

大家有没有什么想法?

**Comment by jizhongling** [comment]
@xiehuc 在网页上直接用js能成功吗？是不是对Firefox支持不好呢？用V8可以吗？

**Comment by xiehuc** [comment]
关键是rsa加密，每次输出都不一样，没法调啊。这和firefox肯定没关系，应该还是哪里差了一些。

El Psy Congroo

在 2015年1月25日，23:21，Zhongling Ji <notifications@github.com> 写道：

**Comment by noobfish** [comment]
不管能不能修复,都要感谢@xiehuc 的努力

**Comment by foxprodos** [comment]
腾迅真是贱啊。

**Comment by juvevood** [comment]
狗日的腾讯！！！

**Comment by noobfish** [comment]
现在pidgin-lwqq彻底不能用了么？

**Comment by EricInBj** [comment]
@xiehuc dev分支里代码没提交全？  还有，有可能不光是加密方式变了吧，可能URL参数也有了变化？

**Comment by lianxiangru** [comment]
I thought I really input a wrong password and I even changed my password and eventually got the same result. It comes out that the reason is Tencent changes their algorithm..

**Comment by xiehuc** [comment]
en，dev代码测试过服务器不认。主要是实验室的活也紧张，结果差得老远了，心理压力很大。根本抽不出2 3天的时间去详细排查

El Psy Congroo

在 2015年1月28日，15:38，Eric <notifications@github.com> 写道：

**Comment by demela** [comment]
感谢xiehuc的努力，腾讯真蛋疼

**Comment by floating-cat** [comment]
我这2天凑巧连上去两次了（v0.4.1，不包括最新的那次dev的提交）……

刚刚下午试了下用 CrossOver 运行 QQ，发现安装和使用起来还是蛮方便的。如果不是介意依赖之类的问题的话，可以试试。

**Comment by theburn** [comment]
今天是1月29号，我的又不能登录了。前几天凑巧登录成功，然后几天都开着，今天发送消息失败，结果关闭后，就登录不上了
是不是要考虑换上手机QQ的协议

**Comment by noobfish** [comment]
反编译android的客户端不知道有没有希望

**Comment by EricInBj** [comment]
好消息好消息，登录的问题解决啦！！！只改了一行代码，哦不，准确说是改了个url参数. 
js_ver变了，不过测试结论是这个参数不起决定作用，改不改一样。
加了个pt_tea，webqq请求时是1, 不知道具体代表什么意义。加上这个参数就神奇般地好了！！！

发了个 pull request。还请 @xiehuc 合并一下。

**Comment by asmca** [comment]
普天同庆！

在 2015年1月29日 下午2:31，Eric <notifications@github.com>写道：

> 好消息好消息，登录的问题解决啦！！！只改了一行代码，哦不，准确说是改了个url参数.
> js_ver变了，不过测试结论是这个参数不起决定作用，改不改一样。
> 加了个pt_tea，webqq请求时是1, 不知道具体代表什么意义。加上这个参数就神奇般地好了！！！
>
> 发了个 pull request。还请 @xiehuc <https://github.com/xiehuc> 合并一下。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xiehuc/pidgin-lwqq/issues/616#issuecomment-71976395>.
>



-- 
Regards,
-suse

**Comment by asmca** [comment]
verified patch From eric.

pidgin-2.10.9-1.el7.x86_64
with latest git pull : lwqq and pidgin-lwqq, 
patch :
https://github.com/xiehuc/lwqq/pull/26


another env. 
pidgin-2.10.7  build from src. on FC15 i386.
latest lwqq and pidgin-lwqq, with same patch.

works.

**Comment by xiehuc** [comment]
thanks @EricInBj 我之前是尝试smartqq的登录方式，加密老复杂了。没搞定。原来webqq的登录方式还能用。我等过一段时间了再去调一调smartqq的登录方式，方便万一webqq被禁用了好立即切换。

**Comment by noobfish** [comment]
@xiehuc 太棒了 感谢你的付出

**Comment by jizhongling** [comment]
由衷感谢@xiehuc和@EricInBj，看来只要有高手在，不拍腾讯折腾

**Comment by linux0ne** [comment]
@EricInBj   具体过程可否详细描述？

**Comment by maosuyun2009** [comment]
为什么我更新了代码，重新编译安装了库，问题还是存在？

**Comment by juvevood** [comment]
问下现在哪个分支的代码可以用？感谢两位大婶的付出！

**Comment by EricInBj** [comment]
@juvevood  lwqq项目 master分支。
@maosuyun2009 请确认更新了lwqq项目。
@linux0ne 其实没啥具体过程，就是用Chrome来调试跟踪了一下webqq登录过程，主要想看密码加密方法及最终请求的 Url、 Cookie、 Http header情况的。中途发现有另一个请求，发现那个请求的参数和lwqq代码里的有点不一样。当时注意到的是js_ver变了。。。于是就。。。。。

**Comment by xiehuc** [comment]
反正就这几点
看自己是不是安装了两份lwqq库，以为自己用的是新的，其实还是旧的。

**Comment by maosuyun2009** [comment]
@xiehuc 多谢，自己傻了，我/usr/lib下和/usr/local/lib下都有lwqq库，我安装到了/usr/lib下面去了。。
