### ISSUE TITLE
无法在自己创建的讨论组里发言

### ISSUE THREAD

**Issue by fireinice** [xiehuc/pidgin-lwqq#617]
发现只要是我自己创建的讨论组（一般是使用手机QQ创建的）内，我都无法发言
使用的是lwqq和pidgin-lwqq master head编译的
06:56:19 PM) Me: test
(06:56:27 PM) Send failed, err(108):
test

**Comment by fireinice** [comment]
相关的debug信息
[Jan 29 18:59:27] ERROR[2746]: internal.c:166 lwqq__process_simple_response: 
	unexpected response 
	http:200, response:
	{"retcode":108,"errmsg":""}

dns[2763]: nobody needs me... =(
[Jan 29 18:59:29] ERROR[2746]: internal.c:166 lwqq__process_simple_response: 
	unexpected response 
	http:200, response:
	{"retcode":108,"errmsg":""}

[Jan 29 18:59:32] ERROR[2746]: internal.c:166 lwqq__process_simple_response: 
	unexpected response 
	http:200, response:
	{"retcode":108,"errmsg":""}

(18:59:32) signals: Signal data for recieved-chat-msg not found!

**Comment by fireinice** [comment]
发现之前建立的是没有问题的，最近建立的会有这个问题

**Comment by xiehuc** [comment]
ok 我晚上调一下看看。

**Comment by xiehuc** [comment]
测试webqq自身也不行，去找tx投诉吧。

**Comment by cocomice** [comment]
不是据说腾讯妖终止webqq的服务么，去年的新闻～

**Comment by fireinice** [comment]
谢谢，辛苦xiehuc了
