### ISSUE TITLE
又无法登录了 Fri Jan 30 09:43:44 CST 2015

### ISSUE THREAD

**Issue by asmca** [xiehuc/pidgin-lwqq#618]
[Jan 30 09:43:13] ERROR[3495]: login.c:393 do_login_back: 
	Unknow error

**Comment by asmca** [comment]
有没有出现类似情况的。。。

**Comment by asmca** [comment]
已经打上commit: https://github.com/xiehuc/lwqq/commit/7a1ad123e8347867fd25e7b587099db8ab1f9e97

**Comment by maosuyun2009** [comment]
@asmca 我的也是这样，pull新的commit还是登录不上

**Comment by asmca** [comment]
昨天打上patch之后就没问题了， 保不齐 昨晚 腾讯那边又改什么参数了。 

难道他们也有人在track 这个项目～

**Comment by EricInBj** [comment]
不是吧。。。。
我网试了一下，退出pidgin，重新登录，是可以的啊。

**Comment by xiehuc** [comment]
unknow error 一般只是网络错误，多试几次

**Comment by jizhongling** [comment]
看到吓了一跳，试了下我的没有任何问题。

**Comment by noteatapples** [comment]
非常感谢，已经可以顺利登录了，补丁很好用。

**Comment by loafer** [comment]
补丁在哪?没找到

**Comment by loafer** [comment]
PPA不更行了吗?

**Comment by lainme** [comment]
@loafer  更新的是liblwqq0，pidgin-lwqq没有做修改。
sudo apt-get update
sudo apt-get install liblwqq0

**Comment by Lavande** [comment]
未更新上面的commit，第一次登录，unknown error，点击reconnect，正常登录了

**Comment by loafer** [comment]
@lainme 谢谢搞定了。但是发现今早又登陆不上了

**Comment by jizhongling** [comment]
@loafer 我的自从更新后一直没有问题，或许使用Launchpad的PPA好一点。

**Comment by loafer** [comment]
@jizhongling不知啥原因，只是提示“unknown error”，不过多试了几次，又登上去了。

**Comment by EricInBj** [comment]
恩，我今天也这情况，unknown error比较多。。。

**Comment by jizhongling** [comment]
@loafer 恩，我现在也出现无数unknown error以致不能登录的情况了。

**Comment by Lavande** [comment]
看错了，@asmca 说的commit我已经更新过，今天一直 unknown error登录不了

**Comment by chengdongdong** [comment]
同样问题，unknown error，狗日的腾讯

**Comment by xiehuc** [comment]
挺头疼的。

**Comment by shmilee** [comment]
点个十几次，总能蹦出验证码的

**Comment by jizhongling** [comment]
@shmilee 还真是。点了12次出来验证码，然后正常登录了。猜测是联网过程有随机性，但肯定不是hash密码有随机性，因为每次是先校验验证码，后核对密码。估计和@EricInBj 改的那个url参数有关。

**Comment by EricInBj** [comment]
@xiehuc  我gdb了一下，发现出unknow的时候， do_login_back的响应是这样的。

311		response = req->response;
(gdb) p response
$1 = 0x4632254632254133 <error: Cannot access memory at address 0x4632254632254133>

**Comment by EricInBj** [comment]
见鬼，这半个多小时完全不出unknow error了。。。

**Comment by EricInBj** [comment]
刚才重启完机器，又出unknow，gdb看到是在  login.c:get_login_sig_back中。 截取g_login_sig的时候结果有问题， 


结果是这样的：


(gdb) p login_sig
$9 = "SM4uAj7IEU9-XzUwIDdGS1RwooJxVqmQ-wH9lOrw1Vyp0mPpqAjEQnY4XpZzR7sD\000g_time.time5=new Date();\r\n\twebLoginReport();\t\r\n\tptui_notifySize(\"login\");\r\n\tif(!curXui){ptui_initFocus(login_form);}\r\n}\r\n</script><title>weblogin</title></head><body onload=\"onPageLoad()\" onc"

**Comment by EricInBj** [comment]
找到报这个错误的根本原因了。在登录的时候，如果不服务器说，这次就不用亲输验证码了。 这时候要带上下面几个参数，其中，pt_verifysession_v1的值从check响应的cookie中取，看代码注册里 @xiehuc  写了句，要处理这个参数，但实际没处理，应该是以前服务器没做严格检查。
好吧，出来混尽早要还，来补上这几个参数吧。。。。我先试试。。

&pt_uistyle=5
&pt_randsalt=0
&pt_vcode_v1=0
&pt_verifysession_v1=d2e7a943d5ae6189e5

**Comment by EricInBj** [comment]
@xiehuc  最近比较忙啊？ 
我这两天断断续续折腾了不少，现在我这边的情况是：
1. 把密码加密方式改成RSA的了，用的JS文件就是你在dev分支里的那个。
2. 不管有没有验证码，登录url都会增加上面贴子里说的pt_verifysession_v1等几个参数，其中pt_verifysession_v1的值有两种情况：
  a). 不需要验证码时，这个的值check请求返回时带的ptvfsession cookie值，其实也就是调用 ptui_checkVC的第五个参数。
   b). 需要验证码时，值为cookie中的verifysession，这个cookie在获取验证码图片，就是getimage的响应中有。
3. 做了如上改动之后，现在不管有无验证码，都报密码错误
4. gdb中在do_login下断点，把生成的url拷出来，开浏览器的隐身模式(没有任何cookie，排除cookie干扰)，请求url，也报密码错误。
5. 如果把第4步请求的URL中的p参数替换成在浏览器中加密（把整个encrypt.js内容贴console中，然后执行 encryption(pwd,pt.salt,vcode）得到的密文。这样就可以登录成功。
6. pt.salt是这样一个串： '\x00\x00\x00\x00\x07\x27\x11\x6b' 直接在console中输出显示 "'k" 。
7. 使用原来代码中lwqq_enc_pwd函数中对 uin的处理结果 _uin 来调用函数加密也不行，看了一下_uin，值为 "\000\000\000\000\a'\021k"
8. 胜利就在眼前了。

**Comment by EricInBj** [comment]
同志们，我这简单测试了几个号，有没有验证码都能正常登录了。
基本不会写C, 还好没改多少地方，照猫画虎拼凑上了，比较恶心，js文件也暂时没放安装目录里，就先不发pull request了。。回头再研究研究。或者 @xiehuc 有时间的时候直接改这边的代码吧。
各位可以临时用我fork的代码编译安装测试，记得把lib/encrypt.js扔到   /tmp下。
好了，回家。。。

**Comment by jizhongling** [comment]
感谢@EricInBj ，辛苦了

**Comment by xiehuc** [comment]
@EricInBj 我也回家过年了，难得蹭邻居的网能上去了。
我干脆加你为协作者得了，另外考虑弄个lwqq的组织么？把pidgin-lwqq和lwqq都放到下面去。

**Comment by EricInBj** [comment]
@xiehuc 原来是回家了啊，我说呢。。
协作者。。可我基本不会C啊。。。照猫画老虎排查排查问题还凑合。。。
目前倒是借着折腾这些事儿学习C，哈哈。
明天要是不出门的话，我先把encrypt.js文件路径写死的问题解决了。请教个问题：我看你之前在pidgin-lwqq的dev分支里引入了这个文件，为什么不是在lwqq里加入这个呢，我觉得这是lwqq所依赖的东西啊，是有什么原因吗？ 我现在不知道把这文件放哪好了。。。
另外，能否邮件或Q联系？ 我的是hotmail邮箱，就是我这ID  @ hotmail.com

**Comment by xiehuc** [comment]
怎么说呢，当时想着lwqq没有一个res文件夹来放这些资源文件。其实你的也是对的。
现在通过添加一个 lwqq_util_load_res 的 api 函数来辅助读取资源文件了。

我已经把你的更新拉进来了，并加入了一些patch。

**Comment by jizhongling** [comment]
@xiehuc @EricInBj 提供一个信息供参考：我5次登录都是出现10个unknown error,第11次成功，不知道有没有什么道理。

**Comment by Lavande** [comment]
ls应该是巧合吧？我这登录了20次都没登录成功。。。。

**Comment by xiehuc** [comment]
新补丁应该能用吧，我都登上去了

Lavande <notifications@github.com>于2015年2月8日星期日写道：

**Comment by EricInBj** [comment]
@jizhongling 确实差不多就是10个unknow error, 因为前十次web qq服务器那边没有要求输入验证码。第11次才会要求的。 @xiehuc 更新了这边的代码，把我的垃圾代码都改好了，哈哈，大家可以更新啦。

**Comment by felixonmars** [comment]
我这里测试良好, 已更新下面的包到 Arch [community] 仓库:

lwqq 0.4.1.20150208-1
pidgin-lwqq 0.4.1.20150208-1

**Comment by jizhongling** [comment]
首先感谢@xiehuc @EricInBj 
但是我安装了Launchpad的更新后，一登录QQ，pidgin就自动退出。
系统：Linux Mint 17.1

**Comment by lainme** [comment]
@jizhongling 我可能少加一个文件……等等再更新一次

**Comment by lainme** [comment]
@jizhongling 我把encrypt.js忘了，你可以自己把它放到/usr/share/lwqq底下，或者等会再更新一次liblwqq0

**Comment by jizhongling** [comment]
谢谢@lainme 的及时回复。可惜我在git clone里找不到encript.js，所以还是等你更新吧。

**Comment by Lavande** [comment]
呜，最新的代码我这编译不了，make出问题了不知道怎么回事……

/home/foxx/Programs/dev/compile_dir/pidgin-lwqq/src/translate.c: In function ‘translate_global_init’:
/home/foxx/Programs/dev/compile_dir/pidgin-lwqq/src/translate.c:11:92: error: ‘RES_DIR’ undeclared (first use in this function)
 #define GLOBAL_SMILEY_PATH(path) (snprintf(path,sizeof(path),"%s"LWQQ_PATH_SEP"smiley.txt",RES_DIR),path)
                                                                                            ^
/home/foxx/Programs/dev/compile_dir/pidgin-lwqq/src/translate.c:417:42: note: in expansion of macro ‘GLOBAL_SMILEY_PATH’
   build_smiley_exp_from_file(smiley_exp, GLOBAL_SMILEY_PATH(path));
                                          ^
/home/foxx/Programs/dev/compile_dir/pidgin-lwqq/src/translate.c:11:92: note: each undeclared identifier is reported only once for each function it appears in
 #define GLOBAL_SMILEY_PATH(path) (snprintf(path,sizeof(path),"%s"LWQQ_PATH_SEP"smiley.txt",RES_DIR),path)
                                                                                            ^
/home/foxx/Programs/dev/compile_dir/pidgin-lwqq/src/translate.c:417:42: note: in expansion of macro ‘GLOBAL_SMILEY_PATH’
   build_smiley_exp_from_file(smiley_exp, GLOBAL_SMILEY_PATH(path));
                                          ^
/home/foxx/Programs/dev/compile_dir/pidgin-lwqq/src/translate.c:11:100: warning: left-hand operand of comma expression has no effect [-Wunused-value]
 #define GLOBAL_SMILEY_PATH(path) (snprintf(path,sizeof(path),"%s"LWQQ_PATH_SEP"smiley.txt",RES_DIR),path)
                                                                                                    ^
/home/foxx/Programs/dev/compile_dir/pidgin-lwqq/src/translate.c:417:42: note: in expansion of macro ‘GLOBAL_SMILEY_PATH’
   build_smiley_exp_from_file(smiley_exp, GLOBAL_SMILEY_PATH(path));
                                          ^
make[2]: *** [src/CMakeFiles/webqq.dir/translate.c.o] Error 1
make[1]: *** [src/CMakeFiles/webqq.dir/all] Error 2
make: *** [all] Error 2

**Comment by lainme** [comment]
@jizhongling 应该可以了。我虚拟机出了问题，显示不出验证码，没法自己测试。

@Lavande 需要先更新lwqq

**Comment by Lavande** [comment]
@lainme lwqq我更新了哇，么的用……

**Comment by jizhongling** [comment]
@lainme 更新了lwqq0，退出重新登录linux，还是崩溃，也可能是我的问题，请问哪里可以找到log file呢？

**Comment by felixonmars** [comment]
有可能和我遇到了同一个问题? #621

**Comment by lainme** [comment]
@jizhongling 刚才有人发邮件说用更新后包就能登录了，所以你遇到的可能是 #621 ，而不是打包的问题。

**Comment by jizhongling** [comment]
@felixonmars  请试下你命令行调用pidgin崩溃不？我命令行工作的很好。

**Comment by lainme** [comment]
@Lavande 会不会是装了多份lwqq？或者清理build目录试试？

**Comment by felixonmars** [comment]
@jizhongling 就是从命令行直接 gdb 启动的... 出现概率比较高, 目测大概 50%.

**Comment by jizhongling** [comment]
@lainme 多谢教我调试。可惜我用命令行和gdb从不崩溃，用GUI链接登录50%崩溃。

**Comment by jizhongling** [comment]
安了现在的Launchpad更新后不崩溃了，感谢@lainme 和其他人。

**Comment by Lavande** [comment]
刚刚跟新了lwqq和pidgin-lwqq，都是dev分支
现在是pidgin一打开就闪退，在命令行运行同样crash，只有一行提示
Segmentation fault (core dumped)

**Comment by lainme** [comment]
@Lavande 用gdb看一下backtrace吧

**Comment by Lavande** [comment]
奇怪。。。带着debug重新编译之后，不崩溃了，无论是从命令行还是从图形界面启动都正常，而且可以登录
