### ISSUE TITLE
dependency 太多了。。能不能搞个script把需要的dependency给安装了。 

### ISSUE THREAD

**Issue by zhaoze1991** [xiehuc/pidgin-lwqq#619]

**Comment by lainme** [comment]
wiki里已经列出了安装的命令

https://github.com/xiehuc/pidgin-lwqq/wiki/Install-From-Source

**Comment by zhaoze1991** [comment]
你好。我看到这个wiki了的。也尝试去折腾了会儿，还是编译失败了。然后就懒得再去折腾。
所以，对于Linux小白用户来说，如果安装方便，对于普及还是有一定帮助的。
谢谢。

**Comment by lainme** [comment]
Ubuntu、Arch和OpenSUSE都有打好的安装包。https://github.com/xiehuc/pidgin-lwqq/wiki/Install-On-Linux

**Comment by zhaoze1991** [comment]
赞

**Comment by xiehuc** [comment]
普及？你想多了。那什么安装麻烦都是借口，関係ない。

El Psy Congroo

在 2015年2月3日，12:08，Zhaoze Zhou <notifications@github.com> 写道：

**Comment by 1dot75cm** [comment]
fedora 也有 ：copr.fedoraproject.org/coprs/mosquito/myrepo

**Comment by lianxiangru** [comment]
2333 there's a jargon: 'ai yong yong, bu yong gun. we do this for free.'

**Comment by zhaoze1991** [comment]
其实我不大理解为啥要支持win和Mac。。难道就是because you can 么。

**Comment by xiehuc** [comment]
因为当时做了linux之后就有群众强烈要求支持mac和win，并且说了一大堆理由。然后我就做了。等我做完了现在估计win和mac下也没人用了，就成现在这样了。

El Psy Congroo

在 2015年2月5日，12:06，Zhaoze Zhou <notifications@github.com> 写道：
