### ISSUE TITLE
启动时崩溃 @a0fa8bf

### ISSUE THREAD

**Issue by tom6740** [xiehuc/pidgin-lwqq#622]
和#621貌似不同…… @86778dc没有问题。

(gdb) bt
#0  0xb7685d3c in __kernel_vsyscall ()
#1  0xb6720307 in __GI_raise (sig=sig@entry=6)
    at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#2  0xb67219c3 in __GI_abort () at abort.c:89
#3  0xb7726b56 in ?? ()
#4  <signal handler called>
#5  0xb4bec39d in vp_link () from /usr/lib/liblwqq.so.0
#6  0xb4be23eb in lwqq_add_event_listener () from /usr/lib/liblwqq.so.0
#7  0xb4c5e9e0 in init_client_events () from /usr/lib/purple-2/libwebqq.so
#8  0xb4c5ede7 in qq_login () from /usr/lib/purple-2/libwebqq.so
#9  0xb6945043 in _purple_connection_new () from /usr/lib/libpurple.so.0
#10 0xb69302e4 in purple_account_connect () from /usr/lib/libpurple.so.0
#11 0xb69326db in purple_account_set_enabled () from /usr/lib/libpurple.so.0
#12 0xb76dfe85 in ?? ()
#13 0xb6b9046c in g_cclosure_marshal_VOID__VOID ()
   from /usr/lib/i386-linux-gnu/libgobject-2.0.so.0
#14 0xb6b8e83b in g_closure_invoke ()
   from /usr/lib/i386-linux-gnu/libgobject-2.0.so.0
#15 0xb6ba0855 in ?? () from /usr/lib/i386-linux-gnu/libgobject-2.0.so.0
#16 0xb6ba8eda in g_signal_emit_valist ()
   from /usr/lib/i386-linux-gnu/libgobject-2.0.so.0
#17 0xb6ba90d5 in g_signal_emit ()
   from /usr/lib/i386-linux-gnu/libgobject-2.0.so.0
#18 0xb70ce4bd in gtk_widget_activate ()
   from /usr/lib/i386-linux-gnu/libgtk-x11-2.0.so.0
#19 0xb6fc1c7f in gtk_menu_shell_activate_item ()
   from /usr/lib/i386-linux-gnu/libgtk-x11-2.0.so.0
#20 0xb6fc20bf in ?? () from /usr/lib/i386-linux-gnu/libgtk-x11-2.0.so.0
#21 0xb6fb6e52 in ?? () from /usr/lib/i386-linux-gnu/libgtk-x11-2.0.so.0
#22 0xb6faebac in ?? () from /usr/lib/i386-linux-gnu/libgtk-x11-2.0.so.0
#23 0xb6b8d394 in ?? () from /usr/lib/i386-linux-gnu/libgobject-2.0.so.0
#24 0xb6b8e83b in g_closure_invoke ()
   from /usr/lib/i386-linux-gnu/libgobject-2.0.so.0
#25 0xb6ba0751 in ?? () from /usr/lib/i386-linux-gnu/libgobject-2.0.so.0
#26 0xb6ba8a52 in g_signal_emit_valist ()
   from /usr/lib/i386-linux-gnu/libgobject-2.0.so.0
#27 0xb6ba90d5 in g_signal_emit ()
   from /usr/lib/i386-linux-gnu/libgobject-2.0.so.0
#28 0xb70cf8fc in ?? () from /usr/lib/i386-linux-gnu/libgtk-x11-2.0.so.0
#29 0xb6facf49 in gtk_propagate_event ()
   from /usr/lib/i386-linux-gnu/libgtk-x11-2.0.so.0
#30 0xb6fad45d in gtk_main_do_event ()
   from /usr/lib/i386-linux-gnu/libgtk-x11-2.0.so.0
#31 0xb6e1f189 in ?? () from /usr/lib/i386-linux-gnu/libgdk-x11-2.0.so.0
#32 0xb6a9fda4 in g_main_context_dispatch ()
   from /lib/i386-linux-gnu/libglib-2.0.so.0
#33 0xb6aa00c9 in ?? () from /lib/i386-linux-gnu/libglib-2.0.so.0
#34 0xb6aa0479 in g_main_loop_run ()
   from /lib/i386-linux-gnu/libglib-2.0.so.0
#35 0xb6fac135 in gtk_main ()
   from /usr/lib/i386-linux-gnu/libgtk-x11-2.0.so.0
#36 0xb76d19d0 in main ()

**Comment by xiehuc** [comment]
因为头文件改了，所以需要重新编译pidgin-lwqq，只编译lwqq不行。

tom6740 <notifications@github.com>于2015年2月8日星期日写道：

**Comment by tom6740** [comment]
谢谢！刚才咋没想到捏。。。现在好了。
