### ISSUE TITLE
make  出错

### ISSUE THREAD

**Issue by xming4321** [xiehuc/pidgin-lwqq#623]
[ 96%] Built target lwqq
[ 96%] Built target lwqq-static
Linking C executable lwqq-cli
../lib/liblwqq.so.0.4.2: undefined reference to `lwqq_js_enc_pwd'
../lib/liblwqq.so.0.4.2: undefined reference to `lwqq_js_load_buffer'
collect2: error: ld returned 1 exit status
make[2]: *** [src/lwqq-cli] Error 1
make[1]: *** [src/CMakeFiles/lwqq-cli.dir/all] Error 2
make: *** [all] Error 2

cmake 通过了但是make出现上面的问题，请问该怎么办

**Comment by xming4321** [comment]
确切是 我make lwqq出的问题

**Comment by xming4321** [comment]
系统为ubuntu

**Comment by xiehuc** [comment]
是不是没装mozjs，现在必须依赖。cmake的忘改了还是可选依赖所以编译失败了。

El Psy Congroo

在 2015年2月27日，19:48，十一文 <notifications@github.com> 写道：

**Comment by xming4321** [comment]
libmozjs-17.0-0 is already the newest version.
libmozjs-17.0-0-dbg is already the newest version.
libmozjs-17.0-bin is already the newest version.
libmozjs-17.0-bin-dbg is already the newest version.
libmozjs-17.0-dev is already the newest version.
libmozjs-24-0 is already the newest version.
libmozjs-24-0-dbg is already the newest version.
libmozjs-24-bin is already the newest version.
libmozjs-24-bin-dbg is already the newest version.
libmozjs-24-dev is already the newest version.
libmozjs185-1.0 is already the newest version.
libmozjs185-dev is already the newest version.
libgjs0e is already the newest version.


 还是上面一样的错

**Comment by xiehuc** [comment]
要删了build重新编译。或者用-DWITH_MOZJS=On 强制开启。


El Psy Congroo

在 2015年2月28日，10:54，十一文 <notifications@github.com> 写道：
