### ISSUE TITLE
ubuntu安装遇到问题

### ISSUE THREAD

**Issue by universewill** [xiehuc/pidgin-lwqq#627]
下载后解压缩，进入解压文件夹，执行mkdir build
然后cd build进入build文件夹，
然后执行cmake ..    出现下面的错误：

 Configuring incomplete, errors occurred!
See also "/home/universe/Downloads/pidgin-lwqq-master/CMakeFiles/CMakeOutput.log".

查看log文件我观察到：
  collapse library dir [/usr/lib/gcc/x86_64-linux-gnu/4.8] ==> [/usr/lib/gcc/x86_64-linux-gnu/4.8]
  collapse library dir [/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu] ==> [/usr/lib/x86_64-linux-gnu]
  collapse library dir [/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib] ==> [/usr/lib]
  collapse library dir [/lib/x86_64-linux-gnu] ==> [/lib/x86_64-linux-gnu]
  collapse library dir [/lib/../lib] ==> [/lib]
  collapse library dir [/usr/lib/x86_64-linux-gnu] ==> [/usr/lib/x86_64-linux-gnu]
  collapse library dir [/usr/lib/../lib] ==> [/usr/lib]
  collapse library dir [/usr/lib/gcc/x86_64-linux-gnu/4.8/../../..] ==> [/usr/lib]
  implicit libs: [stdc++;m;c]
  implicit dirs: [/usr/lib/gcc/x86_64-linux-gnu/4.8;/usr/lib/x86_64-linux-gnu;/usr/lib;/lib/x86_64-linux-gnu;/lib]
  implicit fwks: []

请问如何解决？

**Comment by lainme** [comment]
Configuring incomplete, errors occurred!
这段前面有什么。

**Comment by mhohai** [comment]
[推荐用lainme的源，直接安装](https://github.com/xiehuc/pidgin-lwqq/wiki/Install-On-Linux#ubuntu-via-ppa)
> $ sudo add-apt-repository ppa:lainme/pidgin-lwqq
$ sudo apt-get update
$ sudo apt-get install pidgin-lwqq
