### ISSUE TITLE
Linux mint17.1  64位PPA安装pidgin-lwqq遇到问题!

### ISSUE THREAD

**Issue by Byronvis** [xiehuc/pidgin-lwqq#628]
![screenshot from 2015-03-17 18 30 33](https://cloud.githubusercontent.com/assets/8474239/6685316/c188acaa-ccd3-11e4-9b06-7adab40c1e08.png)

**Comment by lainme** [comment]
不明白为什么64位的系统会试图装32位的包。我的虚拟机没法装64位，没法测试。

**Comment by Byronvis** [comment]
64位不能兼容32位的应用么？

**Comment by xiehuc** [comment]
难以置信, 要不然就去launchpad.net 手工下载deb包安装吧.

**Comment by Byronvis** [comment]
不可思议！！今天就装上了。
![screenshot from 2015-03-18 12 27 52](https://cloud.githubusercontent.com/assets/8474239/6702690/548ef0e0-cd6a-11e4-9aa9-3d3a3a2f6a00.png)
