### ISSUE TITLE
群消息的通知没有gnome集成.

### ISSUE THREAD

**Issue by kexul** [xiehuc/pidgin-lwqq#630]
只有普通聊天有那个酷炫的ｇｎｏｍｅ效果，群消息没有效果，请问怎么解决？

**Comment by xiehuc** [comment]
我以前给那个gnome shell插件提交过patch，但貌似被禁用了。

El Psy Congroo

在 2015年3月29日，21:05，kexul <notifications@github.com> 写道：

**Comment by wsdjeg** [comment]
能坚持一直做确实不容易，我闲杂就把这里当做时代码仓库，备份学习资料的
