### ISSUE TITLE
怎么在pidgin-lwqq里面输入中文？

### ISSUE THREAD

**Issue by cook123** [xiehuc/pidgin-lwqq#633]
操作系统是manjaro，输入管理器是fcitx

**Comment by lainme** [comment]
这个问题与pidgin-lwqq无关。如果你在别的gtk程序里能输入，在pidgin里也会能够输入。如果不行，去搜索fcitx设置方面的内容，通常要装fcitx-gtk2/fcitx-gtk3等，再设置环境变量。

**Comment by cook123** [comment]
我已经设置了变量并且在其他程序，比如mousepad里面就能输入

**Comment by cook123** [comment]
浏览器也能输入中文

**Comment by lainme** [comment]
fcitx-gtk2/fcitx-gtk3都装了？其它gtk3程序能输入只有pidgin不行？pidgin里换用其它协议可以么？因为pidgin-lwqq只是一个协议插件，如果只有pidgin不能输入，那有可能是pidgin的问题。

**Comment by lainme** [comment]
GTK_IM_MODULE等的值最好设为fcitx

**Comment by cook123** [comment]
已经解决了，是没重新启动的缘故，重新启动之后就可以输入中文了
