### ISSUE TITLE
登录不了

### ISSUE THREAD

**Issue by M0Dark** [xiehuc/pidgin-lwqq#634]
老是账号或密码错误

**Comment by mhohai** [comment]
去试试：[w.qq.com](http://w.qq.com)

**Comment by gaohaoliang** [comment]
+1 登录不了

**Comment by mhohai** [comment]
不想重复，去试试：[w.qq.com](http://w.qq.com) 登录不了，表示你帐号有问题！

**Comment by xiehuc** [comment]
我专门试了一下可以登录。你们机器上不是用的最新的代码吧。

**Comment by behind1231** [comment]
不上去，老是 提示Wrong verify code

**Comment by xiehuc** [comment]
好的我调试一下，因为我的默认没出验证码，所以没测到

**Comment by haoliangxxx** [comment]
@mhohai 两天前(2015-04-15) pidgin-qq 登录不了, 一直在用 webqq 的

**Comment by haoliangxxx** [comment]
可能我的版本(0.4.2.1)不是最新(0.4.3)的, 等两天更新再反馈吧。

**Comment by mhohai** [comment]
@haoliangxxx 我的一直没出问题，ubuntu 我什么都没改动的表示，我只是怀疑是不是QQ设置的问题。

**Comment by xiehuc** [comment]
0.4.3是昨天晚上刚赶工出来的。我也是一直没问题，然后为了测验证码，输入错密码几次，然后就登不上去了。

**Comment by felixonmars** [comment]
已更新 0.4.3 到 Arch [community]，新版在我这里可以登陆了（旧版不行）。

**Comment by felixonmars** [comment]
PS: 我有一个帐号登陆一直是 103 错误：
```
[Apr 17 12:02:41] ERROR[27105]: login.c:496 set_online_status_back:
        unexpected response
        http:200, response:
        {"retcode":103,"errmsg":""}
```

**Comment by xiehuc** [comment]
WQQ 也是吗？这个要比对服务器发送回来的消息，没法测试阿。

**Comment by mhohai** [comment]
@xiehuc 你这情况有两个建议，一是删除pidgin的缓存。 二是去腾讯官网改下密码啥的，腾讯经常各种保护。

**Comment by felixonmars** [comment]
似乎是腾讯的服务器问题，登陆很多遍之后好了……
