### ISSUE TITLE
聊天消息，手机和lwqq同时使用lwqq会丢失一两个消息

### ISSUE THREAD

**Issue by faonecze** [xiehuc/pidgin-lwqq#636]
两个一起开的情况下lwqq会丢消息，手机收到了lwqq没有收到。每次跟朋友聊天都会丢一两个，因为发现这个问题都不敢在使用lwqq的时候关掉手机，就怕丢消息，这是因为什么造成的呢？与自身网络环境有关吗？还是因为其他地方？

**Comment by xiehuc** [comment]
我也是一直开着手机QQ的，lwqq就是方便打字快些。

至于你说的，webqq好友聊天不像群聊天没有一个seq机制检查是否丢消息。一般是webqq自己就没收到消息。你可以用webqq观察下是否也有此现象

El Psy Congroo

在 2015年4月21日，20:41，faonecze <notifications@github.com> 写道：

**Comment by EricInBj** [comment]
我基本也这样用，同时开手机Q，主要是有时候对方发来图片，会显示[File not found]的情况。
lwqq 确实有时候会丢消息，大部分时候是会比手机慢。
我猜，丢消息会不会是有时候wqq的连接不稳定，然后手机先收着消息，几秒内，wqq的连接还没恢复，这时候服务器那边会认为这个消息已经被手机读取，且当前无其它在线客户端，后面wqq上线了，也不会收到推送？

**Comment by faonecze** [comment]
对了。

忽略的组（兼容）recent插件：
输出等级：
发送relink间隔（m）

这三项是代表什么意思呢？

**Comment by xiehuc** [comment]
Wiki -> User Guide

faonecze <notifications@github.com>于2015年4月23日星期四写道：
