### ISSUE TITLE
添加群失败

### ISSUE THREAD

**Issue by felixonmars** [xiehuc/pidgin-lwqq#637]
这个问题其实很久了，不过最近错误信息里更有信息量了一点，所以我还是提出来，看看有没有什么办法？

```
[Apr 22 11:39:55] ERROR[17357]: internal.c:172 lwqq__process_simple_response:
        unexpected response
        http:200, response:
        {"retcode":100001,"tips":"\u0027vfy\u0027 为必填字段!"}
```

**Comment by EricInBj** [comment]
看了一下，w.qq.com 上不能添加群啊。。。 web2.qq.com 好像抽风，登进去连好友列表那个界面都出不来。。。

**Comment by xiehuc** [comment]
用手机加吧，lwqq就是方便打字的。

El Psy Congroo

在 2015年4月22日，11:57，Eric <notifications@github.com> 写道：

**Comment by linux0ne** [comment]
我这里也经常是这个样子，添加群出现错误。
