### ISSUE TITLE
关于提高Send failed, err(-1) 重发成功率的建议

### ISSUE THREAD

**Issue by csbde** [xiehuc/pidgin-lwqq#640]
最近在发消息时经常会有发送消息失败的问题。
记得前面看到过说 当出现Send failed, err(-1) 时，lwqq已经帮助重发了几次的。
但实际情况是发现在重发过程中，如果使用原本的消息重发很容易失败，或者根本不可能成功。 怀疑是消息编码或字数有问题。 实测在原有消息后添加1到数个空格或其他的不可见字符反而容易成功。

所以建议：

能否添加在重发时自动在后面添加一些不可见字符以提高重发的成功率。
最好可以自己设置当消息失败时的重发次数。

**Comment by xiehuc** [comment]
这么神奇，可以考虑。send fail 主要是好友消息还是群消息？

El Psy Congroo

在 2015年5月12日，11:01，csbde <notifications@github.com> 写道：

**Comment by csbde** [comment]
是在好友消息里面Send failed, 我也觉得挺神奇的，但实测有效果

**Comment by xiehuc** [comment]
ok，我近期加上去

**Comment by xiehuc** [comment]
已采纳
