### ISSUE TITLE
Windows下无法成功编译lwqq

### ISSUE THREAD

**Issue by NetworkOffice** [xiehuc/pidgin-lwqq#641]
我已经按照wiki上面说的配置好开发环境了，但是总在cmake上面出错：

c:\work\lwqq_root\lwqq\build>cmake .. -G "MSYS Makefiles" -DWIN32_LIBS_DIR=`lwqq
_root/win32-dev` -DWITHOUT_ASYNC=On -DWITH_LIBUV=Off
-- The C compiler identification is GNU 3.4.5
-- The CXX compiler identification is GNU 3.4.5
-- Check for working C compiler: C:/MinGW/bin/gcc.exe
-- Check for working C compiler: C:/MinGW/bin/gcc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/MinGW/bin/g++.exe
-- Check for working CXX compiler: C:/MinGW/bin/g++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could NOT find Sphinx (missing:  Sphinx-build_EXECUTABLE Sphinx-apidoc_EXECUT
ABLE)
CMake Error at C:/Program Files/CMake/share/cmake-3.2/Modules/FindPackageHandleS
tandardArgs.cmake:138 (message):
  Could NOT find CURL (missing: CURL_LIBRARY CURL_INCLUDE_DIR)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.2/Modules/FindPackageHandleStandardArgs.c
make:374 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.2/Modules/FindCURL.cmake:61 (FIND_PACKAGE
_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:72 (find_package)

-- Configuring incomplete, errors occurred!
See also "C:/work/lwqq_root/lwqq/build/CMakeFiles/CMakeOutput.log".

lwqq的issuse找不到了，因此只好写到这个板块里面了，还望谅解。

**Comment by NetworkOffice** [comment]
没人知道吗？

**Comment by NetworkOffice** [comment]
前一个问题我已经解决了，是win32-dev路径的问题，但是现在make出错：
c:\work\lwqq_root\lwqq\build>make
[  2%] Building C object lib/CMakeFiles/lwqq.dir/login.c.obj
In file included from c:/work/lwqq_root/lwqq/lib/login.h:14,
                 from c:/work/lwqq_root/lwqq/lib/login.c:26:
c:/work/lwqq_root/lwqq/lib/type.h:1: error: stray '\239' in program
c:/work/lwqq_root/lwqq/lib/type.h:1: error: stray '\187' in program
c:/work/lwqq_root/lwqq/lib/type.h:1: error: stray '\191' in program
In file included from c:/work/lwqq_root/lwqq/lib/http.h:14,
                 from c:/work/lwqq_root/lwqq/lib/login.c:28:
c:/work/lwqq_root/lwqq/lib/type.h:1: error: stray '\239' in program
c:/work/lwqq_root/lwqq/lib/type.h:1: error: stray '\187' in program
c:/work/lwqq_root/lwqq/lib/type.h:1: error: stray '\191' in program
In file included from c:/work/lwqq_root/lwqq/lib/login.c:28:
c:/work/lwqq_root/lwqq/lib/http.h:16: error: redefinition of typedef 'LwqqAsyncE
vent'
c:/work/lwqq_root/lwqq/lib/login.h:16: error: previous declaration of 'LwqqAsync
Event' was here
c:/work/lwqq_root/lwqq/lib/http.h:93: error: redefinition of typedef 'LwqqHttpRe
quest'
c:/work/lwqq_root/lwqq/lib/type.h:27: error: previous declaration of 'LwqqHttpRe
quest' was here
In file included from c:/work/lwqq_root/lwqq/lib/async.h:12,
                 from c:/work/lwqq_root/lwqq/lib/login.c:32:
c:/work/lwqq_root/lwqq/lib/type.h:1: error: stray '\239' in program
c:/work/lwqq_root/lwqq/lib/type.h:1: error: stray '\187' in program
c:/work/lwqq_root/lwqq/lib/type.h:1: error: stray '\191' in program
In file included from c:/work/lwqq_root/lwqq/lib/login.c:32:
c:/work/lwqq_root/lwqq/lib/async.h:43: error: redefinition of typedef 'LwqqAsync
Event'
c:/work/lwqq_root/lwqq/lib/http.h:16: error: previous declaration of 'LwqqAsyncE
vent' was here
c:/work/lwqq_root/lwqq/lib/async.h:43: error: redefinition of typedef 'LwqqAsync
Event'
c:/work/lwqq_root/lwqq/lib/http.h:16: error: previous declaration of 'LwqqAsyncE
vent' was here
c:/work/lwqq_root/lwqq/lib/async.h:188: error: redefinition of typedef 'LwqqExte
nsion'
c:/work/lwqq_root/lwqq/lib/http.h:17: error: previous declaration of 'LwqqExtens
ion' was here
In file included from c:/work/lwqq_root/lwqq/lib/utility.h:3,
                 from c:/work/lwqq_root/lwqq/lib/login.c:33:
c:/work/lwqq_root/lwqq/lib/type.h:1: error: stray '\239' in program
c:/work/lwqq_root/lwqq/lib/type.h:1: error: stray '\187' in program
c:/work/lwqq_root/lwqq/lib/type.h:1: error: stray '\191' in program
In file included from c:/work/lwqq_root/lwqq/lib/login.c:34:
c:/work/lwqq_root/lwqq/lib/internal.h:61: error: redefinition of typedef 'json_t
'
c:/work/lwqq_root/lwqq/lib/json.h:110: error: previous declaration of 'json_t' w
as here
c:/work/lwqq_root/lwqq/lib/internal.h:62: error: redefinition of typedef 'LwqqAs
yncEvent'
c:/work/lwqq_root/lwqq/lib/async.h:43: error: previous declaration of 'LwqqAsync
Event' was here
c:/work/lwqq_root/lwqq/lib/internal.h:62: error: redefinition of typedef 'LwqqAs
yncEvent'
c:/work/lwqq_root/lwqq/lib/http.h:16: error: previous declaration of 'LwqqAsyncE
vent' was here
c:/work/lwqq_root/lwqq/lib/internal.h:63: error: redefinition of typedef 'LwqqCl
ient'
c:/work/lwqq_root/lwqq/lib/type.h:26: error: previous declaration of 'LwqqClient
' was here
c:/work/lwqq_root/lwqq/lib/internal.h:64: error: redefinition of typedef 'LwqqVe
rifyCode'
c:/work/lwqq_root/lwqq/lib/type.h:295: error: previous declaration of 'LwqqVerif
yCode' was here
c:/work/lwqq_root/lwqq/lib/internal.h:65: error: redefinition of typedef 'LwqqHt
tpRequest'
c:/work/lwqq_root/lwqq/lib/http.h:93: error: previous declaration of 'LwqqHttpRe
quest' was here
c:/work/lwqq_root/lwqq/lib/internal.h:65: error: redefinition of typedef 'LwqqHt
tpRequest'
c:/work/lwqq_root/lwqq/lib/http.h:93: error: previous declaration of 'LwqqHttpRe
quest' was here
In file included from c:/work/lwqq_root/lwqq/lib/info.h:14,
                 from c:/work/lwqq_root/lwqq/lib/login.c:36:
c:/work/lwqq_root/lwqq/lib/type.h:1: error: stray '\239' in program
c:/work/lwqq_root/lwqq/lib/type.h:1: error: stray '\187' in program
c:/work/lwqq_root/lwqq/lib/type.h:1: error: stray '\191' in program
In file included from c:/work/lwqq_root/lwqq/lib/info.h:15,
                 from c:/work/lwqq_root/lwqq/lib/login.c:36:
c:/work/lwqq_root/lwqq/lib/msg.h:14: error: redefinition of typedef 'LwqqAsyncEv
ent'
c:/work/lwqq_root/lwqq/lib/internal.h:62: error: previous declaration of 'LwqqAs
yncEvent' was here
c:/work/lwqq_root/lwqq/lib/msg.h:14: error: redefinition of typedef 'LwqqAsyncEv
ent'
c:/work/lwqq_root/lwqq/lib/http.h:16: error: previous declaration of 'LwqqAsyncE
vent' was here
c:/work/lwqq_root/lwqq/lib/login.c: In function `do_login':
c:/work/lwqq_root/lwqq/lib/login.c:202: warning: implicit declaration of functio
n `lwqq_js_load_buffer'
make[2]: *** [lib/CMakeFiles/lwqq.dir/login.c.obj] Error 1
make[1]: *** [lib/CMakeFiles/lwqq.dir/all] Error 2
make: *** [all] Error 2
求帮忙看看，是不是代码的问题啊，还有那个mozjs怎么安装啊？

**Comment by xiehuc** [comment]
webqq已经不行了，在windows下编译没什么实质意义。

cook green <notifications@github.com>于2015年5月21日星期四写道：

**Comment by NetworkOffice** [comment]
关键是qq的windows版本占用太大，webqq也没有广告，挺好的，求作者帮忙解决一下。

**Comment by xiehuc** [comment]
关键是一个能用一个不能用，webqq根本不能发送讨论组消息，以前也有人这么找我做windows的支持，后来都不了了之了。所以我就没有再弄了。

要没广告的话可以用TM。我也是在windows下用TM的。

cook green <notifications@github.com>于2015年5月25日星期一写道：

**Comment by mhohai** [comment]
@NetworkOffice 你需要http://dldir1.qq.com/qqfile/qq/QQ6.7Light/13466/QQ6.7Light.exe
