### ISSUE TITLE
Pdigin登录QQ总是提示“Wrong username or password”

### ISSUE THREAD

**Issue by NetworkOffice** [xiehuc/pidgin-lwqq#642]
我QQ号和密码都正确了啊
pdigin-lwqq用的是wiki上面已经编译好的

**Comment by lainme** [comment]
用的5.0么？试试4.x版本的

**Comment by NetworkOffice** [comment]
我用的就是4.x的

**Comment by xiehuc** [comment]
我用最新版的可以登录，没有出现问题，是不是你的要求输出验证码了？

cook green <notifications@github.com>于2015年5月22日星期五写道：

**Comment by NetworkOffice** [comment]
对的

**Comment by NetworkOffice** [comment]
一直要求验证码

**Comment by NetworkOffice** [comment]
关键是你那些下载链接都挂掉了，编译我也编译不出来，源代码文件编码有问题，而且代码逻辑也有问题

**Comment by xiehuc** [comment]
验证码的问题我有空再弄一下吧，你可以先用网页版的webqq多登录几次，登录到不提示验证码的时候再用lwqq登。

最近有毕业设计，时间是真没有了。

反正我觉得现在webqq基本上处于残废状态，没法用。

cook green <notifications@github.com>于2015年5月25日星期一写道：

**Comment by xiehuc** [comment]
0.6.1 should fix it
