### ISSUE TITLE
无法登录，错误提示：10000

### ISSUE THREAD

**Issue by xlfjn** [xiehuc/pidgin-lwqq#643]
我使用的pidgin-lwqq和lwqq均为ArchLinux官方源提供的0.5.0版
忘记从何时起，没法登陆了。
（来自pidgin调试窗口，经删减）
```
(20:30:20) webqq: https://ssl.ptlogin2.qq.com/check?[length=140]
(20:30:25) webqq: https://ssl.captcha.qq.com/getimage?[length=110]
(20:30:29) webqq: https://ssl.ptlogin2.qq.com/login?[length=738]
(20:30:30) connection: Connection error on 0x88b3908 (reason: 0 description: 登录失败，请稍后再试。(10000))
(20:30:30) webqq: ptuiCB('1','0','','0','登录失败，请稍后再试。(10000)', '[length=9]');

(20:30:30) account: Disconnecting account [length=9] (0x831fea8)
(20:30:30) connection: Disconnecting connection 0x88b3908
(20:30:30) connection: Destroying connection 0x88b3908
```
（来自pidgin -f）
```
[May 28 20:30:14] WARNING[15296]: http.c:744 check_multi_info: 
	async retcode:28 Timeout was reached
We need verify code image: sHfaybONHRw99Ro7KP57gzloTQUNp0XuV84NSjGRVp3Uxvkdses-7A**
[May 28 20:30:30] WARNING[15296]: login.c:308 do_login_cb: 
	Server busy! Please try again
```
此帐号在w.qq.com能够正常登陆。

**Comment by rtlix** [comment]
我也有这个问题，但是，在连外网的时候pidgin-lwqq可以用。
可是连ipv6教育网用goagent全局代理时（export），就是这问题

01:21:17) connection: Connection error on 0x205f610 (reason: 0 description: 登录失败，请稍后再试。(10000))
(01:21:17) account: Disconnecting account $myaccount (0x19d63e0)
(01:21:17) connection: Disconnecting connection 0x205f610

我的lwqq和pidgin-lwqq也都是0.5.0，git版

如果这道原因后可以告知一下吗？谢谢！

**Comment by mhohai** [comment]
@rtlix 全局代理，一般不是紧浏览器加个别软件全局么？
浏览器还有pac呢

你都说了代理原因

**Comment by rtlix** [comment]
@mhohai 可奇怪的是，用的都是同样的代理，为什么firefox可以正常使用webqq，而pidgin-lwqq就有这10000错误，CA.crt已导入系统信任证书机构
虽然有可能是代理的原因，但具体为什么会出现返回10000这个问题，或者说为什么代理有可能导致lwqq出现这个问题

**Comment by xiehuc** [comment]
最近在做毕设，过几天看看。

El Psy Congroo

在 2015年6月1日，20:14，rtlix <notifications@github.com> 写道：

**Comment by xlfjn** [comment]
我没有设置代理，都是直连的（好吧，经过路由器一层NAT）。

**Comment by mhohai** [comment]
今天通过朋友（前腾讯员工）反馈了，webQQ无法发送讨论组消息，及Linux的问题，不过大家不要报太大希望…

**Comment by rtlix** [comment]
只要腾讯能专门给linux留个可靠稳定好用的协议就好了，话说这几天也准备考试呢

**Comment by lainme** [comment]
暂时切换到0.4.x版本吧。0.5.0确实有这个问题

**Comment by xlfjn** [comment]
升级到0.6.0，能够登陆了。
