### ISSUE TITLE
发送图片在手机QQ上显示的是一个sae的链接而非图片？？？

### ISSUE THREAD

**Issue by gmg137** [xiehuc/pidgin-lwqq#645]
使用dev分支发送图片，在电脑上可以正常显示，但在手机上显示的却是一个sae的图片链接，求说明？？？

**Comment by xiehuc** [comment]
上传服务器。还没改完，
https://github.com/xiehuc/pidgin-lwqq/wiki/simple-user-guide#upload-server

在 2015年6月5日 下午5:52，gmg137 <notifications@github.com>写道：

**Comment by gmg137** [comment]
报个bug，直接通过[对话]-[发送文件] 或直接将文件拖入对话框，然后不选择文件直接[取消]或者关闭窗口会造成pidgin崩溃。
