### ISSUE TITLE
能否添加一个可以在聊天对话框中双击图片会按图片原大小显示出来的功能

### ISSUE THREAD

**Issue by kd83kdi93** [xiehuc/pidgin-lwqq#650]
有些图片是全屏截图，想看大图还要先下载，使用起来不太方便。

**Comment by xiehuc** [comment]
做不到

El Psy Congroo

在 2015年6月10日，21:48，bikli <notifications@github.com> 写道：

**Comment by xiehuc** [comment]
你把窗口放大就行了

El Psy Congroo

在 2015年6月10日，21:48，bikli <notifications@github.com> 写道：
