### ISSUE TITLE
讨论组发消息失败都不提示了…  天杀的鹅厂！

### ISSUE THREAD

**Issue by mhohai** [xiehuc/pidgin-lwqq#651]
我想说的是：以前发错了提示失败，我还知道失败了。
如今不提示失败却不代表成功，大家小心……

@xiehuc 我很喜欢你的这个项目，可是我觉得你不该被这个项目禁锢，我觉得你应该找个时间将这个项目转为组织，然后去经营你的未来，你的梦想。我等着你回来，那天我们建一个属于自己的IM…

致意，问候！

**Comment by xiehuc** [comment]
我也想转啊，都没人。不过我以后工作了估计就没时间搞了。现在要和实验室的学弟联系还得用上。我是直接把讨论组的人迁移到QQ群上的，群貌似还能正常用。

El Psy Congroo

在 2015年6月11日，16:45，gshmu <notifications@github.com> 写道：

**Comment by mhohai** [comment]
lwqq不是还有你管了，有个词叫：撒手不管……

**Comment by fireinice** [comment]
看日志，还是有错误返回的，只是在pidgin里不显示了，好像是因为最近的commit造成的。个人希望还是把发送失败显示出来。

**Comment by xiehuc** [comment]
我等毕设完了再改改吧。

El Psy Congroo

在 2015年6月15日，11:43，fireinice <notifications@github.com> 写道：

**Comment by xiehuc** [comment]
lwqq 的 dev 分支修复
