### ISSUE TITLE
gnome3的集成不好用啊

### ISSUE THREAD

**Issue by raphaeltao** [xiehuc/pidgin-lwqq#654]
如题，都按照设置的，还是在底下显示的

**Comment by xiehuc** [comment]
gnome3的不是在底下显示那是在哪里。。

2015-07-07 14:35 GMT+08:00 raphael <notifications@github.com>:

**Comment by raphaeltao** [comment]
额，不是那意思，我是说就是底下正常提示的一栏，并没有你截图的效果呢

xiehuc <notifications@github.com>于2015年7月7日星期二写道：

> gnome3的不是在底下显示那是在哪里。。
>
> 2015-07-07 14:35 GMT+08:00 raphael <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>:
>
> > 如题，都按照设置的，还是在底下显示的
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/xiehuc/pidgin-lwqq/issues/654>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xiehuc/pidgin-lwqq/issues/654#issuecomment-119232957>.
>


-- 
From Raphael＇s iphone

**Comment by xiehuc** [comment]
看你版本了。

https://extensions.gnome.org/extension/214/pidgin-conversation-integration/

2015-07-07 23:23 GMT+08:00 raphael <notifications@github.com>:

**Comment by raphaeltao** [comment]
嗯，我装的就是这个，我明天去看一下版本，不记得3.x了

xiehuc <notifications@github.com>于2015年7月7日星期二写道：

> 看你版本了。
>
> https://extensions.gnome.org/extension/214/pidgin-conversation-integration/
>
> 2015-07-07 23:23 GMT+08:00 raphael <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>:
>
> > 额，不是那意思，我是说就是底下正常提示的一栏，并没有你截图的效果呢
> >
> > xiehuc <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>于2015年7月7日星期二写道：
>
> >
> > > gnome3的不是在底下显示那是在哪里。。
> > >
> > > 2015-07-07 14:35 GMT+08:00 raphael <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>');>>:
> > >
> > > > 如题，都按照设置的，还是在底下显示的
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <https://github.com/xiehuc/pidgin-lwqq/issues/654>.
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/xiehuc/pidgin-lwqq/issues/654#issuecomment-119232957>.
> >
> > >
> >
> >
> > --
> > From Raphael＇s iphone
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/xiehuc/pidgin-lwqq/issues/654#issuecomment-119237849>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xiehuc/pidgin-lwqq/issues/654#issuecomment-119241500>.
>


-- 
From Raphael＇s iphone

**Comment by raphaeltao** [comment]
我的是gnome3.9.90版本的，支持吗？

在 2015年07月07日 23:37, xiehuc 写道:
> 看你版本了。
>
> https://extensions.gnome.org/extension/214/pidgin-conversation-integration/ 
>
>
> 2015-07-07 23:23 GMT+08:00 raphael <notifications@github.com>:
>
> > 额，不是那意思，我是说就是底下正常提示的一栏，并没有你截图的效果呢
> >
> > xiehuc <notifications@github.com>于2015年7月7日星期二写道：
> >
> > > gnome3的不是在底下显示那是在哪里。。
> > >
> > > 2015-07-07 14:35 GMT+08:00 raphael <notifications@github.com
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>:
> > >
> > > > 如题，都按照设置的，还是在底下显示的
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <https://github.com/xiehuc/pidgin-lwqq/issues/654>.
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > 
> <https://github.com/xiehuc/pidgin-lwqq/issues/654#issuecomment-119232957>.
> >
> > >
> >
> >
> > --
> > From Raphael＇s iphone
> >
> > —
> > Reply to this email directly or view it on GitHub
> > 
> <https://github.com/xiehuc/pidgin-lwqq/issues/654#issuecomment-119237849>.
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/xiehuc/pidgin-lwqq/issues/654#issuecomment-119241500>.
>

-- 
 From Raphael

**Comment by xiehuc** [comment]
太老了，我用的3.14 你得找找以前支持3.9的老pidgin插件

El Psy Congroo

在 2015年7月8日，12:03，raphael <notifications@github.com> 写道：

**Comment by xiehuc** [comment]
另外不要用gnome3的开发版。你自己看下插件的metadata.json吧。反正属于个别现象。

El Psy Congroo

在 2015年7月8日，12:03，raphael <notifications@github.com> 写道：
