### ISSUE TITLE
lwqq版本不匹配，找到0.6.1，需要0.6.0

### ISSUE THREAD

**Issue by faonecze** [xiehuc/pidgin-lwqq#655]
刚刚看到有lwqq升级，升级后发现如图提示，如何处理这个问题呢？
![2015071500002](https://cloud.githubusercontent.com/assets/4413476/8698782/5e7131a0-2b33-11e5-9807-fb76296d9160.png)

**Comment by lainme** [comment]
我忘了合并pidgin-lwqq的上游代码了……等一会，我再更新一次

**Comment by faonecze** [comment]
嗯，好的～
