### ISSUE TITLE
代码： 如何将聊天窗口里的gif动画文件保存到本地，并可实现再次转发给好友

### ISSUE THREAD

**Issue by linux0ne** [xiehuc/pidgin-lwqq#657]
系统：ubuntu

在与他人聊天的过程中，常常见到比较有意思的gif动画文件，这时，如果想保存到本地，以便于将来再次发送给别人，或者是用作它途的话，你会发现pidgin-lwqq并不能保存成功。（这也有可能是pidgin本身就不具备这个功能）

它会以PNG为默认的保存类型来保存文件为一个图片，当然是不动的了！即使是把扩展名改为gif也不行。

所以大家想想办法，看看如何处理呢？

PS：在发帖之前我在网上也搜集了一下相关的消息，无论是关于pidgin的，还是pidgin-lwqq的，都没有有用的建议，于是在这里期待大家的代码分享，希望写出具体的步骤和完整的程序：一来学习如何为pidgin-lwqq写插件，二来学习一下大家的编程思维。

**Comment by linux0ne** [comment]
呵，如果xiehc大神可以关注这个帖子就好了，如果能写出完整的插件编写过程，那就发财了，嘻嘻。

**Comment by mhohai** [comment]
不要太贪了，能收文字消息我就满足了 :8ball:
