### ISSUE TITLE
无法登陆，终端输出 unexpected response 于 login.c:454 set_online_status_cb

### ISSUE THREAD

**Issue by xiaokangwang** [xiehuc/pidgin-lwqq#659]
终端输出：
[Jul 29 07:28:25] WARNING[10354]: http.c:755 check_multi_info: 
	async retcode:28 Timeout was reached
Verify code: !UTE
[Jul 29 07:28:32] ERROR[10354]: login.c:454 set_online_status_cb: 
	unexpected response 
	http:200, response:
	{"retcode":100005,"errmsg":""}

GUI显示为unknown error

**Comment by mhohai** [comment]
[你使用网页能登录么？](http://w.qq.com)

**Comment by xiaokangwang** [comment]
也有问题，那我先和疼逊反馈去了。感谢回复！

**Comment by mhohai** [comment]
@xiaokangwang 我的早晨也无法登录，后来被逼改了密码，还是不可以就虚拟机了，然后现在恢复了。。。

**Comment by xiaokangwang** [comment]
不是lwqq的问题是疼逊的问题
