### ISSUE TITLE
我和服务器之间传输的信息是加密的吗？

### ISSUE THREAD

**Issue by Lavande** [xiehuc/pidgin-lwqq#661]
刚刚掉线提示QQ在另一个地点登录，而我并没有在其它地方登录。
除了用lwqq我并未在其它任何地方使用过，所以不太可能QQ密码被盗，当然目前也没有被盗的迹象。
不排除提示信息错误的可能。
不过现在有点担心，因为和别人共用一个无线网络，所以很关注自己传输数据的安全性……

**Comment by EricInBj** [comment]
账户设置-高级-SSL

**Comment by Lavande** [comment]
谢谢提示，不过还有个问题就是那个选项是SSL(encrypt on chat)，是针对聊天内容加密，那么登录时候密码是否加密呢？（密码是比对md5不是传送明文的吧？）

**Comment by Lavande** [comment]
刚刚勾上了这个选项，然后pidgin频繁crash……基本上就十几秒的时间就崩溃了

**Comment by theburn** [comment]
今天我也发生了这个问题，开了不到3分钟，就Pidgin 就crash了。连续几次都是这样

**Comment by EricInBj** [comment]
@Lavande  密码不传输明文。


似乎开SSL确实会增加crash的概率，昨天下午我开了，总挂掉，不过现在有好久没挂了。

**Comment by edhelas** [comment]
Hi, I'm not using pidgin-lwqq with SSL enabled but I still have crash issue using the latest trunk version.
Seems that there is an infinite loop issue or something similar here.

**Comment by mhohai** [comment]
@edhelas which system you are using?  ubuntu, [try lainme](https://github.com/xiehuc/pidgin-lwqq/wiki/Install-On-Linux)  and test at web QQ.
