### ISSUE TITLE
为什么打开pidgin登录qq没过几秒瞬间关闭了？？

### ISSUE THREAD

**Issue by faonecze** [xiehuc/pidgin-lwqq#662]
没有任何提示，也没有看到报错的提示～

**Comment by faonecze** [comment]
[Aug 19 17:34:02] WARNING[6737]: http.c:755 check_multi_info: 
	async retcode:28 Timeout was reached
[Aug 19 17:34:03] WARNING[6737]: http.c:755 check_multi_info: 
	async retcode:28 Timeout was reached
段错误


---------终端下启动后最后错误是这个～

**Comment by saltduck** [comment]
我的情况也一样，/var/log/syslog 最后一行报错：

    pidgin[17357]: segfault at 0 ip 00007f4afdc864c0 sp 00007fff7693ea40 error 6 in liblwqq.so.0.6.1[7f4afdc6c000+38000]

**Comment by mhohai** [comment]
什么系统？  如何安装的？

**Comment by saltduck** [comment]
Ubuntu 15.04 64bit, 从PPA安装的

**Comment by mhohai** [comment]
@saltduck 先试下WEBQQ，然后尝试删除家目录配置再试试。（删除到回收站或者备份删除）

**Comment by theburn** [comment]
不知道是不是服务器的问题，什么都没动的情况下，这两天登陆又正常了
