### ISSUE TITLE
讨论组发消息提示错误108

### ISSUE THREAD

**Issue by Frederick888** [xiehuc/pidgin-lwqq#664]
前两天似乎还没这个问题

Request headers:

	POST /channel/send_discu_msg2 HTTP/1.1
	Host: d.web2.qq.com
	Cookie: *hidden*
	User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/33.0.1750.152 Safari/537.36
	Accept: */*
	Accept-Language: zh-cn,zh;q=0.9,en;q=0.8
	Accept-Encoding: gzip,deflate,x-gzip
	Connection: keep-alive
	Referer: http://d.web2.qq.com/proxy.html?v=20130916001&callback=1
	Content-Length: 425
	Content-Type: application/x-www-form-urlencoded

Response headers and body:

	HTTP/1.1 200 OK
	Server: tws
	Date: Sun, 06 Sep 2015 14:58:24 GMT
	Content-Type: text/plain; charset=utf-8
	Content-Length: 29
	Connection: close
	Cache-Control: no-cache

	{"retcode":108,"errmsg":""}

**Comment by mhohai** [comment]
很久的问题了，http://w.qq.com 也不能发送。。。
